spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mplus?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  application:
    name: domain

server: 
  port: 8071
  servlet:
    context-path: /domain

logging:
  level:
    com.young : debug

user: 
  url: "http://localhost:8081/user/peo/"

management:
  endpoints:
    web:
      exposure:
        include:
        - refresh,health,info
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@127.0.0.1:10000/eureka/
  instance:
    prefer-ip-address: true # 在eureka页面显示ip